import React from "react";
import Chart from "../components/chart/chart";
import Head from "next/head";
const chart = () => {
  return (
   <>
   <Head>
        <title>Chart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <Chart/>
   </>
  )
}

export default chart
